# Generated by Django 4.2.3 on 2023-08-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('DNI', models.IntegerField()),
                ('nombres_madre', models.CharField(max_length=50)),
                ('apellidos_madre', models.CharField(max_length=50)),
                ('nombres_padre', models.CharField(max_length=50)),
                ('apellidos_padre', models.CharField(max_length=50)),
            ],
        ),
    ]
